- .gitignore
- flare/gp.py
- flare/gp_algebra.py
- flare/gp_from_aimd.py
- flare/md_run.py
- flare/otf.py
- flare/output.py
- flare/qe_util.py
- tests/test_OTF.py
- tests/test_gp_from_aimd.py
A new class Output is set to replace the original output module. The class opens a log file and two xyz files at the init function and closes all files in conclude_run() function. All the original functions in the output module now become function members in the Output class, with the same arguments.
new class for output and write atomic configurations to xyz files
The new class avoid open/close the log file too often and also automatically back up the old log file if it exists before the current run starts.
write_xyz_config(...) function is also added to print configs in xyz format. It is called in the record_state function in otf.py and md_run.py.
Completely:
- issue #36
> new output class and add configuration output in ".xyz" format

- tests/test_OTF.py
- tests/test_qe_util.py
Now skips unit tests which have no hope of succeeding if the user does not have the PWSCF_COMMAND environment variable:
Also tightened up an import statement in test_qe_util. Didn't think it warranted an issue.
> Now skips tests with QE if PWSCF_COMMAND is not found

- .gitignore
- .travis.yml
- README.md
- requirements.txt
- tests/test_mgp.py
Add Travis CI and codecov for automatic testing and coverage reports.
> CI with coverage

- flare/gp_from_aimd.py
- flare/output.py
I have been iterating with train_gp_from_AIMD and have found that the Output module only flushing its buffer periodically and therefore intermittently writing to the output files, while computationally more efficient in general, is undesirable for watching it run in real-time. I propose adding a few arguments to the Output class which make it write instantly to the output if the user wishes to follow output in real time and otherwise does not change the functionality of the module.
> Added flexibility to user to frequency of output writing

- .gitignore
- README.md
- setup.py
I added a setup.py. It seems to work (tested in barebones Docker image).
Additionally, I have edited the README to reflect the eased installation. I also added CP2K instructions and a Read the Docs badge.
Closes #66
> Add setup.py for easy installation

- .gitignore
- README.md
- setup.py
Added flare to pypi as mir-flare.
Updated instructions in README.
More badges.
> Register on pypi, more badges

- tests/test_flare_io.py
- tests/test_vasp_util.py
The test_vasprun.xml is small and unconverged so it produces a warning. I suppressed this warning along with one that warns about a missing POTCAR file.
> Quick fix to suppress pymatgen warnings

- flare/gp.py
- tests/test_gp.py
- tests/test_gp_from_aimd.py
I decided to grandfather in `maxiter` and `opt_algorithm` as arguments because I thought that breaking everybody's scripts would be rude. I do think that they belongs in the  `opt_params` argument so we can add it in later if we want. Perhaps we could include a warning that `opt_algorithm` and `maxiter` will be deprecated with V 1.0 and to use `opt_params` instead if they are passed in as arguments.
Closes #91
> WIP: GP now takes opt_params argument

- flare/gp_algebra.py
PR to not modify -- or only minimally refactor -- code, but add in docstrings, comments, and typehints to improve code readability
> WIP: Docstrings and typehints

- flare/otf.py
- tests/test_OTF_qe.py
- tests/test_OTF_qe_par.py
> Added & unit tested store_dft_output

- flare/otf.py
If you use a previously trained GP, which kept track of species by their atomic number (for instance, hydrogen as 1 and oxygen as 8), and then wanted to run an OTF run on it, the OTF engine by default encodes the species into integers: so, if hydrogen came first, it would be designated as 0, and if oxygen second, it would be designated as 1. This would cause the model to think oxygen was hydrogen and hydrogen was something it had never seen before. (This example is not hypothetical-- I caught this bug trying to use a previously existing GP to power an OTF run).
I'm pretty sure that this line is a holdover from before we changed over to species-as-integers, which is now built into struc anyway by assigning elements to their atomic numbers.
> Bugfix: OTF ignores structure species, when using pre-trained GP

- flare/ase/calculator.py
- flare/ase/logger.py
- flare/ase/otf.py
- flare/ase/otf_md.py
- tests/test_ase_setup/test_otf.py
fixed the ASE logger issue reported in #133
> Ase interface - close #133

- flare/gp.py
- flare/gp_algebra.py
Closes #147 
Gives the option to print hyperparameters, likelihood, and likelihood gradient during hyperparameter optimization. Defaults to false.
> give the option to print hyperparameters to console

- flare/gp.py
- flare/gp_from_aimd.py
- flare/output.py
- tests/test_files/gpfa_parse_test.out
- tests/test_gp_from_aimd.py
Adds:
- `parse_trajectory_trainer_output` to `gp_from_aimd.py` which allows for easy parsing on both a frame-by-frame level as well as on the GP level.
- A unit test for the parser, and a test file for it to run on.
Changes:
- Certain `output.py` functions now have their arguments changed to allow optional input. This should change nothing about the way they are used in other scripts, but makes for cleaner GPFA output parsing.
- Minor cosmetic change to GaussianProcess' training_statistics method.
> Added GPFA parser function to gp_from_aimd

- flare/predict.py
Emergency fix for #176. We should add a unit test later to check that predict.py correctly updates the force and std attributes of structure.
> fix predict

- tests/test_predict.py
Closes #178 ; tests the writing methods and the selective atom functionality.
> Predict.py now has 100% coverage

- flare/gp.py
- requirements.txt
- tests/fake_gp.py
- tests/test_gp.py
In the event of having a model that has bad training data you'd no longer like to use. Removes by internal index of force data; re-computes matrices, updates the internal training label np arrays, and also updates the global data labels. This addition is 100% covered by a unit test which starts with dummy data, makes predictions, adds data, makes new predictions, removes the data, and ensures that the changes this made to the GP were fully reversed.
> Add, test method to remove force data from a gp

- requirements.txt
Travis logs indicate that pytest is at too low a version (perhaps due to a change in some requirement by another library). I have fixed this by adding a minimum version to pytest in the requirements.txt.
> Attempt to solve unit tests failing due to pytest

- flare/env.py
- flare/gp.py
- tests/test_env.py
- env.py should now be backwards compatible with old atomic environment objects without a cutoffs mask attribute
- Clean up PEP8 compliance for `env.py` and `test_env.py`
> [WIP]Add backwards compatibility for pickled envs

- flare/env.py
- flare/gp.py
- tests/test_env.py
AtomicEnvironments can now get their associated force from the structure they were built from.
Should simplify scripts. I modified one GP function where a force will always be input to the function- making a PR to highlight this change as something most people would find useful in their scripts, as handling forces and environments seperately can get a bit unwieldly.
> Env now has force attribute

- flare/gp.py
- flare/gp_algebra.py
- flare/rbcm.py
- tests/test_rbcm.py
Under construction. RBCMs have been excised from the `xyz_loop_in_kernel` branch so that they can be used by a wider audience to take advantage of faster hyperparameter training.
PR Review:
- @nw13slx  ensure that no changes have compromised the function of the RBCMs.
> Integrate RBCMs onto development branch

- flare/kernels/mc_simple.py
- flare/kernels/sc.py
- tests/test_kernel.py
For faster calculations and easier comparison to EAM potentials, add a 2+MB kernel (notably, excluding the three-body contribution).
> Add 2+MB Kernel

- flare/ase/calculator.py
- flare/ase/otf.py
- flare/otf.py
1. Add an option `force_only` in otf, to allow training with only atomic forces. This is from the considerations below:
- **A minor point:** the calculation will be faster
- **In some situations the energies are not very useful:** for example, in the SiC system, for different stackings like 3C & 4H, the bulk energy difference is controversial, i.e. the dE is so small that different pp or different DFT codes sometimes give opposite ordering. At such cases, the inclusion of energy is a bit misleading.
- **One last but could be important:** since we've been using the zero mean, we have to consider the energy shift when including global energy as labels. I think at this moment we should use constant mean instead of zero mean for energy. It seems to me that this constant shift can be treated …
> Add option for `force_only` & Add `set_atoms`

- .travis.yml
- flare/ase/calculator.py
- flare/mgp/mapxb.py
- lammps_plugins/pair_mgp.cpp
- setup.py
- tests/test_env.py
Fixes #261 by calling `ase.Calculator.calculate()` from `FLARE_Calculator.calculate()` [as required by ASE](https://gitlab.com/ase/ase/-/blob/88b895511bcbc972092539858d43519a3870cb86/ase/calculators/calculator.py#L785-787).
> Fix ASE calculator returning stale forces (#261)

- flare/ase/otf.py
* Allows an ase calculator to be given as input to the ase otf constructor. This makes it possible to avoid a deepcopy in the `from_ase_atoms` method, which is needed for non-picklable C++ calculators
* Removes a duplicate method in ase otf
> Add optional calculator input to ase otf constructor

- flare/ase/otf.py
- flare/otf.py
- flare/utils/learner.py
* New inputs to otf:
* `update_style`: "add_n" is the default and adds the N highest-uncertainty atoms to the training set, as before; "threshold" adds all atoms above a given threshold.
* `update_threshold`: sets the threshold for `update_style = "threshold"`, and can be different from the `std_tolerance_factor` that triggers DFT calls.
> Give the option in otf to add all atoms above a specified threshold

- flare/struc.py
- tests/test_struc.py
Stress is now included as an argument to the `Structure` object, so structures can be instantiated with the stress property.
Unit tests have been updated so that serialization / deserialization into JSON includes checking for this field.
Run [Black](https://pypi.org/project/black/) on your local machine.
Note that the CI system will run all the above checks. But it will be much more
efficient if you already fix most errors prior to submitting the PR.
> Add stress argument to struc, serialization

- flare/gp_from_aimd.py
- tests/test_gp_from_aimd.py
Adapted from the Pymatgen PR template.
`TrajectoryTrainer` now has an `include_energies` argument which adds in structures labeled by energy during the active learning and passive learning training loops whenever frames are added.
Run [Black](https://pypi.org/project/black/) on your local machine.
Note that the CI system will run all the above checks. But it will be much more
efficient if you already fix most errors prior to submitting the PR.
> GPFA now can include energies

- PULL_REQUEST_TEMPLATE.md
- flare/ase/calculator.py
- flare/ase/nosehoover.py
- flare/ase/otf.py
- flare/dft_interface/vasp_util.py
- flare/gp.py
- flare/lammps/lammps_calculator.py
- flare/otf_parser.py
- flare/parameters.py
- flare/predict.py
- flare/rbcm.py
- flare/struc.py
- requirements.txt
- setup.py
- tests/fake_gp.py
- tests/test_ase_otf.py
- tests/test_flare_io.py
- tests/test_gp.py
- tests/test_grid_kernel.py
- tests/test_mgp.py
- tests/test_rbcm.py
- tests/test_struc.py
- tests/test_vasp_util.py
Include a summary of major changes in bullet points:
* Fix #298 
* Fix #299 by removing `set_atoms` in `FLARE_Calculator`, because in `ase/otf.py: as_dict`, setting calculator by `self.atoms.calc = flare_calc` assigns the atoms to the calculator, without changing the `results` dict, and this method is no longer needed in the current ASE version.
Before a pull request can be merged, the following items must be checked:
Run [Black](https://pypi.org/project/black/) on your local machine.
Note that the CI system will run all the above checks. But it will be much more
efficient if you already fix most errors prior to submitting the PR.
> Bugfix: opt_algorithm for #298, and write_model for #299

- flare/dft_interface/cp2k_util.py
Fixed variables in flare/dft_interface/cp2k_util.py to be consistent with arguments passed by the otf module, and with the rest of the dft utils
Closes #315
> Fixed variables in flare/dft_interface/cp2k_util.py to be consistent 

- CMakeLists.txt
- README.md
- docs/source/installation/install.rst
- requirements.txt
This PR allows to installing flare without loading any modules, thus avoid the case where users have different module version on different clusters that might cause various compatibility issues. 
Three small changes are made in this PR:
- Add python 3.8 to the cmake file
- Add Conda's `include` folder into the search directories in cmake, such that the header files (e.g. `mkl.h`) installed by conda can be found. 
- Increase numpy version upper bound to 1.22 (1.23 has compatibility issue with numba)
---
The compiler tools and libraries required by the flare c++ code are installed by conda, instead of loading from modules. The new installation recipe is as below:
1. Create a new conda env with python<=3.8
```bash
conda create --name flare python=3.8
conda activate flare
```
2. Install …
> Compilers and libraries from conda instead of module load

- flare/otf.py
Include a summary of major changes in bullet points:
* Feature 1
Change calculate_efs and calculate_energy to instance variables in otf.py
* Fix 1
Address #312
> change calculate_efs and calculate_energy to instance variables

- .github/workflows/flare.yml
- README.md
- flare/learners/otf.py
- lammps_plugins/compute_flare_std_atom.cpp
- lammps_plugins/kokkos/pair_flare_kokkos.cpp
- lammps_plugins/pair_flare.cpp
- tests/test_lammps.py
Add fixes to `otf.py` to integrate CP2K with FLARE. Also may address issue 47 in flare_pp: [mir-group/flare_pp#47](https://github.com/mir-group/flare_pp/issues/47) 
• Fix 1: Replace deepcopy with temporarily-generated instance of CP2K
• Fix 2: Fix dump of dft calculator. 
• Supports `write_model = 4` for offline training 
• Tested with CP2K versions 6.1 and 2023.1 
Before a pull request can be merged, the following items must be checked:
Run [Black](https://pypi.org/project/black/) on your local machine.
- If this PR fixes bugs, update version number to a.b.c+1
- If this PR adds new features, update version number to a.b+1.0
- If this PR includes significant changes in framework or interface, update version number to a+1.0.0
Note that the CI system will run all the above checks. But it …
> Fix pickling errors of CP2K within OTF training

- flare/bffs/sgp/sparse_gp.py
- src/flare_pp/bffs/sparse_gp.cpp
- src/flare_pp/descriptors/descriptor.cpp
- tests/get_sgp.py
Bug fixes: 
1. Kuu_jitter was not saved
2. The sparse descriptors initialization could be duplicated so its length is 1 longer than it is supposed to
> bug fixes: Kuu_jitter, sparse_descriptor initialization

- flare/md/fake.py
The FakeDFT method appeared to be really slow for large input files.
This was because the calculate method in FakeDFT read the entire file each call and then selects the frame it needs.
Here, the calculate method was changed to only read the frame from the file it actually needs.
This speeds up the FakeDFT calculator significantly.
> Update FakeDFT to only import relevant frame

- flare/io/output.py
Time step is set to 0.5 fs inMD
Origin print :
*-Frame: 1
Simulation Time:      0.001 ps
updated print:
*-Frame: 1
Simulation Time:     0.0005 ps
> Update output.py: fix time printing, with the time step with 0.5 fs

- flare/descriptors/env.py
- flare/utils/parameter_helper.py
- flare/utils/parameters.py
- requirements.txt
- tests/test_grid_kernel.py
* removes unspecified np.ints and np.floats (deprecated in recent versions of numpy)
* relaxes numpy requirement in requirements.txt
> relax numpy requirement

- .github/workflows/flare.yml
- lammps_plugins/README.md
- lammps_plugins/kokkos/pair_flare_kokkos.cpp
- lammps_plugins/pair_flare.cpp
As of a recent update to the LAMMPS development branch, LAMMPS does not allow the `neigh full newton on` combo. The full/half flag doesn't affect the actual neighbor list anyways, so I've updated the pair styles to allow for the half flag.
> Switch to neigh half flag for Kokkos

- src/flare_pp/bffs/sparse_gp.cpp
Prevents users from hitting the segfault described in #395
> check internal matrices are consistent

- flare/learners/lmpotf.py
Adapted from the Pymatgen PR template.
Fix the type hint, it can either be a list of float or a single float. so I change it to a union.
N/A
N/A
N/A
> Update Type Hint for energy_correction

- flare/md/lammps.py
- tests/test_lammps.py
This pull request introduces a utility function to ensure compatibility between LAMMPS and SGP energy calculations when single atom energies are present in the model.
* [`flare/md/lammps.py`](diffhunk://#diff-17aa21d58ab5f781f2839d94e237b6133cb3bfe14452e1c7d54d935570da8bf6R483-R506): Added a new utility function `add_single_atom_energies()` to correctly handle energy offsets from single atom contributions
* Applied this function consistently in both instances of energy correction within `check_sgp_match()`
* Added clear documentation explaining that LAMMPS output energies do not inherently include single atom energy contributions
* Added test for the utility function
When using `pair_style flare` with LAMMPS, the potential energy reported by LAMMPS does not include the single atom energy …
> Add helper function for single atom energy correction for lammps energy

- CMakeLists.txt
Updated the JSON download method to pull a newer version from the official repo. This fixes an issue on the Colab tutorial, which somehow ends up with CMake 4.1 through scikit-build-core and conflicts with the older JSON's CMake version requirement.
> JSON update

- flare/bffs/mgp/mapxb.py
- flare/descriptors/env.py
- flare/io/output.py
- flare/utils/__init__.py
- pyproject.toml
The unused nptyping dependency was causing numpy<2 to be required.
Also bumped the minor-minor version.
> Remove nptyping dependency
